Remove posix specific idioms
DanielG/cabal-helper pull request #104
Opened 2020-04-25 21:53 UTC by jneira

Maybe there was a reason for using posix specific env vars and commands? Also, not sure if `createHOME` makes sense with these changes.

2020-04-26 08:18 UTC, DanielG requested changes
Ok, so the point of that whole dance is that some distros (nix, I think) make it such that $HOME doesn't actually exist since they consider it a bug for a package build to want to read from it. However we explicitly need `cabal` to be able to use it's state directory in `$HOME/.cabal`! So we have to create a directory for cabal to use.

Since I was too lazy to generate a .cabal/config file with all the paths changed from $HOME to the tempdir I just set `$HOME`, but since there isn't a setHomeDirectory this isn't going to work on windos.

Looking at `Distribution.Client.Config` there seems to be a `CABAL_DIR` envvar that overrides .cabal, so I think we can just use that instead of bending $HOME, provided we don't use $HOME anywhere else.

A quick grep reveals that of course we also use `XDG_CACHE_HOME` and fall back to $HOME if that doesn't exist. Now since on windos we're unlikely to encounter the nonexistent home directory problem we could just ignore that, but I would ask that you just create a directory for that in the tempdir too.

2020-04-26 08:18 UTC, DanielG commented on tests/CompileTest.hs
>    setEnv "HOME" home
Since you're using getHomeDirectory above but `setEnv "HOME"` here this is unlikely to be portable.

2020-04-26 21:41 UTC, jneira commented
Mmm, ok, just to be sure i understood it, we should:
* replace `setupHOME` with a new action `setupCabalDir`. It could set the `CABAL_DIR` env var to `$TEMP/compile-test-cabal-dir` *if it is not already set*, removing all the previous content
* create a new action `setupXDGHome`: similar to previous one but setting `XDG_HOME` with `$TEMP/compile-test-xdg-home`

2020-05-01 16:56 UTC, DanielG commented
> * replace `setupHOME` with a new action `setupCabalDir`. It could set the `CABAL_DIR` env var to `$TEMP/compile-test-cabal-dir` _if it is not already set_, removing all the previous content

I'm not sure where you get the "not already set thing" from? I would just override it. If a user is setting CABAL_DIR for god knows what reason we still don't want to mess with it here.

> * create a new action `setupXDGHome`: similar to previous one but setting `XDG_HOME` with `$TEMP/compile-test-xdg-home`

I would do (psuedo code):

```
createTemp "compile-test" $ \temp -> do
    let cabal_dir = temp </> "cabal"
    let cache_dir = temp </> "cache" 
    mapM_ (createDirectory True) [cabal_dir, cache_dir]
    setEnv "CABAL_DIR" cabal_dir
    setEnv "XDG_CACHE_HOME" cache_dir
```

call that setupTestEnv or something :)

2020-05-01 17:12 UTC, DanielG commented
> I'm not sure where you get the "not already set thing" from? I would just override it. If a user is setting CABAL_DIR for god knows what reason we still don't want to mess with it here.

Oh, shoot. I see now I was checking for the nonex case in order to still be able to use the cabal store and our executable cache normally! Ok only set those envvars if $HOME  doesn't exist then.

2020-05-08 20:59 UTC, jneira commented
@DanielG i think the changes requested are done

2020-05-09 00:58 UTC, DanielG approved these changes
Looks great! Could you just push all your PRs into a new branches in my repo so CI runs. I know the setup I have here is a bit funky :) as it doesn't pick up PRs, just branches.

Essentially when we push into branches on GitHub on my repo, GitLab mirrors the changes and kicks of a CI run over there, GitHub then picks up the CI results for the corresponding commits but the same doesn't work for commits (PRs) in other people's repos unfortunately.

You can still create a PR with the source branch in my repo though! So it doesn't really make a difference once you get used to it :)

2020-05-10 17:00 UTC, jneira commented
As the other two pr's, this one has failed due a timeout but it was succesful in my gitlab ci: https://gitlab.com/jneira/cabal-helper/pipelines/144342426

2020-05-11 17:54 UTC, jneira commented
@DanielG ci is green after the build you triggered, could this be merged then?

2020-05-20 07:46 UTC, DanielG requested changes

2020-05-20 07:46 UTC, DanielG commented on tests/CompileTest.hs
> +      setEnv "XDG_HOME" xdgHome
It's just called `HOME`. Not sure where you got the idea that `XDG_HOME` is a thing?

2020-05-20 07:48 UTC, DanielG commented on tests/CompileTest.hs
> +      setEnv "XDG_HOME" xdgHome
Ah, I think you mixed that up with `XDG_CACHE_HOME` which is the equivalent of `~/.cache` whereas `HOME` is `~/`. Like I said earlier you should create a directory for both.

2021-01-11 13:35 UTC, closed without merging